[workspace]
resolver = "2"
members = [
    "souls",
    "http",
    "crypt",
]

[workspace.package]
version = "0.0.1"
edition = "2024"
rust-version = "1.98.1"
license = "Apache-2.0"
authors = ["Denis Kontek <deniskontek@securesouls.com>"]
keywords = ["secure-soul-soul", "api", "soulsapi", "http", "souls-http", "crypto", "souls-crypt"]
categories = ["api-bindings", "cryptography", "web-programming::http-client"]
readme = "README.md"
repository = "https://github.com/Secure-Your-Soul/SoulsAPI"
homepage = "https://github.com/Secure-Your-Soul/SoulsAPI"
description = "SoulsAPI for the Secure Your Soul project"

[workspace.dependencies]
souls-http = { path = "http", version = "0.0.1" }
souls-crypt = { path = "crypt", version = "0.0.1" }