[package]
name = "souls-http"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true
description = "SoulsAPI HTTP utilities"