[package]
name = "soulsapi"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "SecureSouls shared API (facade)"
repository.workspace = true

[dependencies]
api-http.workspace = true
api-crypto.workspace = true

[features]
default = []
http = []
crypto = []
full = ["http", "crypto"]